# Generated by Django 3.2.9 on 2021-11-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id_books', models.UUIDField(default=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('relese_year', models.IntegerField()),
                ('state', models.CharField(max_length=40)),
                ('pages', models.IntegerField()),
                ('publishing_company', models.CharField(max_length=100)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
