# Generated by Django 3.2.9 on 2021-11-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='id_books',
            field=models.UUIDField(default=False, editable=False, primary_key=True, serialize=False),
        ),
    ]
