# Generated by Django 3.2.9 on 2021-11-25 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_id_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='id_books',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
